version: "3.3"
services:
  postgres:
    image: postgres:13
    volumes:
      - 'db-vol:/var/lib/postgresql'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    networks:
      - app
  api-explorer-scalejs-reach:
    build:
      context: ./
      dockerfile: Dockerfile.api-explorer
    networks:
      - app
    volumes:
      - "../API-Explorer:/usr/src/API-Explorer"
    ports:
      - 8082:8080
  api-manager-python:
    build:
      context: .
      dockerfile: Dockerfile.api-manager
    networks:
      - app
    volumes:
      - "../API-Manager:/code"
    ports:
      - 8000:8000
    environment:
      OBP_MANAGER_API_HOST: http://host.docker.internal:8080
      OBP_MANAGER_SECRET_KEY: "change_me"
      OBP_MANAGER_ALLOWED_HOST: "host.docker.internal"
  api-core-scala:
    volumes:
      - "../OBP-API:/usr/src/OBP-API"
    build:
      context: ../
      dockerfile: OBP-Docker/Dockerfile.obp-base
    networks:
      - app
    ports:
      - 8080:8080
networks:
  app:
volumes:
  db-vol: